# -*- coding: utf-8 -*-
"""translator-.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6SY563tfs4EjwbpjrK88aTGnytONj_c
"""

from transformers import pipeline

translator = pipeline("translation_en_to_de")

test = input('enter some text')

res=translator(test)

res

f_m = pipeline('fill-mask')

text = input('enter some text')

res=f_m(text)

res

feature_extraction=pipeline('feature-extraction')

text = 'programming is easy unless you find it'

res=feature_extraction(text)

res

